# Generated by Django 2.0.5 on 2019-11-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_qcpia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importfile',
            name='is_freq',
        ),
        migrations.RemoveField(
            model_name='importfile',
            name='is_freq_es_et',
        ),
        migrations.RemoveField(
            model_name='importfile',
            name='is_opt',
        ),
        migrations.RemoveField(
            model_name='importfile',
            name='is_opt_es_et',
        ),
        migrations.RemoveField(
            model_name='importfile',
            name='is_sp',
        ),
        migrations.RemoveField(
            model_name='importfile',
            name='is_td',
        ),
        migrations.AddField(
            model_name='importfile',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='id_software',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='import_qcpia.Software'),
        ),
    ]
